# Discounted Thompson Sampling & Energy-Adaptive Discounted TS
name: discountedts
gamma: 0.5
eta: 1                     # pseudo-count for unseen arms
energy_adaptive: false     # true = EA-TS
Mf: ${Mf}
init_energy: 3.912023005428146 # initial energy of the agent
