# ε-Greedy (baseline) and Energy-Adaptive ε-Greedy
name: egree
epsilon: 0.2
eta: 1                     # pseudo-count for unseen arms
energy_adaptive: false     # set to true for EA-ε-Greedy
Mf: ${Mf}                  # inherit global forage-cost
init_energy: ${init_energy} # initial energy of the agent
