# Thompson Sampling & Energy-Adaptive TS
name: ts
eta: 1                     # pseudo-count for unseen arms
energy_adaptive: false     # true = EA-TS
Mf: ${Mf}
init_energy: 3.912023005428146 # initial energy of the agent
