# Thompson Sampling & Energy-Adaptive TS
name: ts
eta: 1                     # pseudo-count for unseen arms
energy_adaptive: false     # true = EA-TS
Mf: ${Mf}
init_energy: ${init_energy} # initial energy of the agent
