# UCB1 & Energy-Adaptive UCB
name: ucb
eta: 1                     # pseudo-count for unseen arms
energy_adaptive: false     # true = EA-UCB
Mf: ${Mf}
c: ${c}                    # exploration coefficient (will be set later)
init_energy: 3.912023005428146 # initial energy of the agent
energy_factor_alg: linear
