# Poisson Dynamic Single-Optimal Gaussian
name: poisson_dynamic_single_optimal
n_arms: 4             # number of arms
mu_opt: 0.2       # mean of the single best arm
mu_sub: 0.04    # mean of every other arm
sigma: 0.02       # shared Gaussian noise std-dev
poisson_lambda: 0.05 # lambda parameter for the Poisson distribution
